### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by guolin** [Turbo87/eslint-plugin-chai-expect#2]
My config is 

```
"plugins": [
    "chai-expect", "react", "import"
],
rules: {
"chai-expect/missing-assertion": 0,
"chai-expect/terminating-properties": 0
}
```

but eslint still have error alert for this line

` expect(AV.User.current()).is.not.be.ok;`

**Comment by Daraku** [comment]
Same issue for me

**Comment by kamui** [comment]
Me too.

**Comment by dj-foxxy** [comment]
Me three.

**Comment by josmardias** [comment]
@guolin @MaksymDev @kamui @dj-foxxy 

From docs:  `terminating-properties` - `Prevent calling to.be.ok and other assertion properties as functions`

In other words, this package will alert you if you put a "call" in the ok (the terminating property)
This is _wrong_ and will _alert_: expect(AV.User.current()).is.not.be.ok**()**;
This is _ok_ and will _not alert_: expect(AV.User.current()).is.not.be.ok;

If you're getting an error by doing `is.not.be.ok` is probably because of [eslint no-unused-expression rule](http://eslint.org/docs/rules/no-unused-expressions).

**Comment by josmardias** [comment]
@Turbo87 I think you can close this one

**Comment by ihordiachenko** [comment]
@guolin @MaksymDev @kamui @dj-foxxy you might be interested in this [eslint plugin](https://github.com/ihordiachenko/eslint-plugin-chai-friendly). It overrides the default `no-unused-expressions` rule to make it friendly towards chai expectations.
